kurslitteratur/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import url
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('marketplace.urls')),
    path('admin/', admin.site.urls),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
]

marketplace/urls.py
from django.urls import path

from . import views

app_name = 'marketplace'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('book/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('book/add/', views.add_book, name='add_book'),
    path('book/add/isbn_lookup/', views.isbn_lookup, name='isbn_lookup'),
    path('browse/', views.browse, name='browse'),
]

marketplace/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    isbn = models.CharField(max_length=20) # TODO: Create custom Field type for ISBN
    title = models.CharField(max_length=200)
    authors = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200)
    year = models.IntegerField(default=0)
    language = models.CharField(max_length=200)
    cover_img = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title

    def get_cover_img_path(self):
        if not self.cover_img or self.cover_img == '':
            return "/static/marketplace/images/default_book.png"
        else:
            return self.cover_img

class University(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Programme(models.Model):
    name = models.CharField(max_length=50)
    field = models.CharField(max_length=50)
    code = models.CharField(max_length=50)

    university = models.ForeignKey(University, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Semester(models.Model):
    name = models.CharField(max_length=50)
    year = models.IntegerField(default=0)
    term = models.IntegerField(default=0)

    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)

    semesters = models.ManyToManyField(Semester)
    books = models.ManyToManyField(Book)
    university = models.ForeignKey(University, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

marketplace/forms.py
from django import forms

import selectable.forms as selectable

from .lookups import UniversityLookup, ProgrammeLookup, SemesterLookup, CourseLookup

class UniversityForm(forms.Form):
    university = forms.CharField(
        label='Universitet',
        widget=selectable.AutoComboboxWidget(UniversityLookup),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class ChainedForm(forms.Form):
    university = forms.CharField(
        label='Universitet',
        widget=selectable.AutoComboboxWidget(UniversityLookup),
        required=False,
    )

    programme = forms.CharField(
        label='Program',
        widget=selectable.AutoComboboxWidget(ProgrammeLookup),
        required=False,
    )

    semester = forms.CharField(
        label='Termin',
        widget=selectable.AutoComboboxWidget(SemesterLookup),
        required=False,
    )

    course = forms.CharField(
        label='Kurs',
        widget=selectable.AutoComboboxWidget(CourseLookup),
        required=False,
    )

    #programme2 = selectable.AutoCompleteSelectField(
    #    lookup_class=ProgrammeLookup,
    #    label='Program2',
    #    required=False,
    #    widget=selectable.AutoComboboxSelectWidget
    #)

marketplace/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.

from .models import Book, Programme, University
from .forms import ChainedForm

import isbnlib
import pprint

# Books
class IndexView(generic.ListView):
    template_name = 'marketplace/index.html'
    context_object_name = 'latest_book_list'
    
    def get_queryset(self):
        """
        Return the last five added books
        """
        return Book.objects.order_by('-id')[:5]

class DetailView(generic.DetailView):
    model = Book
    template_name = 'marketplace/detail.html'

def add_book(request):
    return render(request, 'marketplace/add_book.html')

def isbn_lookup(request):
    try:
        # TODO convert ISBN and get metadata
        isbn = request.POST['isbn']

        canonical_isbn = isbnlib.canonical(isbn)
        if isbnlib.is_isbn10(isbn):
            isbn = isbnlib.to_isbn13(isbn)

        if Book.objects.filter(isbn=isbn).count() > 0:
            raise FileExistsError(f'Book with ISBN {isbn} already exists')

        if not isbnlib.is_isbn13(isbn):
            raise ValueError(f'ISBN is not valid: {isbn}')
        else:
            meta = isbnlib.meta(isbn)

        if not meta:
            raise RuntimeError(f'No book found for ISBN: {isbn}')

        assert meta['ISBN-13'] == isbn, 'ISBN of looked up book does not match requested'

        print('------------------------\n Adding book:')    
        print(f'ISBN: {isbn}')
        print(meta)

    except (FileExistsError):
        return render(request, 'marketplace/add_book.html', {
            'isbn': isbn,
            'error_message': "Book already exists",
        })
    except (ValueError):
        return render(request, 'marketplace/add_book.html', {
            'isbn': isbn,
            'error_message': "Invalid ISBN",
        })
        # TODO except if error arises, eg if ISBN is invalid
    except (RuntimeError):
        return render(request, 'marketplace/add_book.html', {
            'isbn': isbn,
            'error_message': "Did not find book with that ISBN",
        })
    except (AssertionError):
        return render(request, 'marketplace/add_book.html', {
            'isbn': isbn,
            'error_message': "The found book did not match the requested ISBN",
        })
    else:
        title = meta['Title']
        authors = meta['Authors']
        publisher = meta['Publisher']
        year = meta['Year']
        language = meta['Language']
        cover_img = f'http://covers.openlibrary.org/b/isbn/{isbn}-M.jpg'

        book = Book.objects.create(
                isbn=isbn,
                title=title,
                authors=authors,
                publisher=publisher,
                year=year,
                language=language,
                cover_img=cover_img
            )
        book.save()
        print(f'Added book {title} to library\n ------------------------')
        # Return to book list
        return HttpResponseRedirect(reverse('marketplace:index'))

# Browsing
def browse(request):

    book_set = []

    if request.GET:
        initial = request.GET

        university = initial.get('university', '')
        programme = initial.get('programme', '')
        semester = initial.get('semester', '')
        course = initial.get('course', '')

        if university != '' and programme != '' and semester != '' and course != '':
            course = University.objects.get(name=university)   \
                        .programme_set.get(name=programme)     \
                        .semester_set.get(name=semester)       \
                        .course_set.get(name=course)           \

            book_set = course.books.all()

        form = ChainedForm(initial=initial)
    else:
        form = ChainedForm()

    context = {
        'form': form,
        'books': book_set
    }

    return render(request, 'marketplace/browse.html', context)

marketplace/templates/marketplace/add_book.html
<!-- templates/marketplace/add_book.html -->
{% extends "marketplace/base.html" %}

{% block title %}Add book{% endblock %}

{% block content %}
<div class="container">
    Add a book by typing the ISBN number below

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'marketplace:isbn_lookup'%}" method="post">
        {% csrf_token %}
        <label for="isbn">ISBN:</label><br>
        <input type="text" id="isbn" name="isbn"><br>
        <input type="submit" value="Submit">
    </form>
</div>     
{% endblock %}

marketplace/templates/marketplace/base.html
<!-- templates/marketplace/base.html -->

<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}My amazing site{% endblock %}</title>
    {% block head %} {% endblock %}

    {% load static %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'marketplace/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'marketplace/css/bootstrap-responsive.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'marketplace/css/base_style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'marketplace/images/favicon.ico' %}"/>
    
    {% block extra-css %}{% endblock %}

</head>

<body>
    <div class="">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'marketplace:index' %}">Kurslitteratur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == '/' %}active{% endif %}">
              <a class="nav-link" href="{% url 'marketplace:index' %}">Hem <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == '/browse/' %}active{% endif %}">
              <a class="nav-link" href="{% url 'marketplace:browse' %}">Böcker</a>
            </li>
            <li class="nav-item {% if request.path == '/book/add/' or request.path == '/book/add/isbn_lookup/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'marketplace:add_book' %}">Lögg till bok</a>
              </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sök</button>
          </form>
        </div>
      </nav>

    <div id="content" class="">
        {% block content %}{% endblock %}
    </div>

    <footer class="footer pt-4 my-md-5 pt-md-5 border-top mt-auto py-3 container" >
        <div class="row">
        <div class="col-12 col-md">
            <img class="mb-2" src="{% static 'marketplace/images/favicon.ico' %}" alt="" width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2020-2020</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Cool stuff</a></li>
            <li><a class="text-muted" href="#">Random feature</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Resource</a></li>
            <li><a class="text-muted" href="#">Resource name</a></li>
            <li><a class="text-muted" href="#">Locations</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Om</h5>
            <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Team</a></li>
            <li><a class="text-muted" href="#">Kontakt</a></li>
            <li><a class="text-muted" href="#">Privacy</a></li>
            <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
        </div>
        </div>
    </footer>

 

    {% block extra-js %}{% endblock %}
</body>
</div>
</html>

marketplace/templates/marketplace/browse.html
<!-- templates/marketplace/browse.html -->
{% extends "marketplace/base.html" %}

{% load selectable_tags %}

{% block title %}Browse{% endblock %}

{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include_ui_theme %}
    {{ form.media.css }}

{% endblock %}

{% block extra-css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'marketplace/css/browse_style.css' %}"/>
{% endblock %}

{% block content %}

<div class="container">
    <h3>Sök efter kurs</h3>

    {% include_jquery_libs %}
    {{ form.media.js }}

    <form action="" method="GET" >
        <!-- {% csrf_token %} -->
        {{ form.as_p }}
        <!--<button class="btn">Submit</button>-->
    </form>

    <br>

    <div class="album py-5">
        <div class="container">
      
          <div class="row">
            {% for book in books %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img class="book_img" src="{{ book.get_cover_img_path }}"/>
                <div class="card-body">
                  <a href="{% url 'marketplace:detail'  book.id %}"><p class="book_title">{{book.title}}</p></a>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">{{book.year}}</small>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra-js %}
    <script type="text/javascript">
        $(document).ready(function() {
            function newParameters(query) {
                query.university = $('#id_university').val();
                query.programme = $('#id_programme').val();
                query.semester = $('#id_semester').val();
                query.course = $('#id_course').val();
            }
            $('#id_programme').djselectable('option', 'prepareQuery', newParameters);
            $('#id_semester').djselectable('option', 'prepareQuery', newParameters);
            $('#id_course').djselectable('option', 'prepareQuery', newParameters);
            
            $(':input[name=university]').bind('djselectableselect', function(event, ui) {
                $('input[name=programme').val('');
                $('input[name=semester').val('');
                $('input[name=course').val('');
            });
            $(':input[name=programme]').bind('djselectableselect', function(event, ui) {
                $('input[name=semester').val('');
                $('input[name=course').val('');
            });
            $(':input[name=semester]').bind('djselectableselect', function(event, ui) {
                $('input[name=course').val('');
            });
            $(':input[name=course]').bind('djselectableselect', function(event, ui) {
                $(this).parents("form").submit();
            });
        });
    </script>
{% endblock %}

marketplace/templates/marketplace/child.html
<!-- templates/marketplace/child.html -->
{% extends "marketplace/base.html" %}

{% block title %}Child HTML Template{% endblock %}

{% block extra-css %}
    {% load static %}
{% endblock %}

{% block content %}
<p>Child HTML Template</p>
{% endblock %}

{% block extra-js %}

{% endblock %}

marketplace/templates/marketplace/detail.html
<!-- templates/marketplace/detail.html -->
{% extends "marketplace/base.html" %}

{% block title %}{{book.title}}{% endblock %}

{% block content %}
    <p>Title: {{book.title}}</p>
    <p>ISBN: {{book.isbn}}</p>
    <p>Authors: {{book.authors}}</p>
    <p>Publisher: {{book.publisher}}</p>
    <p>Year: {{book.year}}</p>
    <p>Language: {{book.language}}</p>

    <img src="{{ book.cover_img }}" />
{% endblock %}

marketplace/templates/marketplace/index.html
<!-- templates/marketplace/index.html -->
{% extends "marketplace/base.html" %}

{% block title %}Index{% endblock %}

{% block extra-css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'marketplace/css/index_style.css' %}"/>
{% endblock %}

{% block content %}
<div class="container">
    {% if latest_book_list %}
        <ul>
        {% for book in latest_book_list %}
            <li><a href="{% url 'marketplace:detail'  book.id %}">{{ book.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No books are available.</p>
    {% endif %}
</div>
{% endblock %}